version: '3.4'

volumes:
    datafiles:

services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: expenseON
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: ExpenseOnHotel
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    environment: 
      - DBHOST=database